### ISSUE TITLE
How to pass Stack Size Parameter in convert()?

### ISSUE THREAD

**Issue by DeaconF** [xwmx/pandoc-ruby#24]
How can i pass stack size parameter (+RTS -K64m -RTS) in PandocRuby.convert()

on command line it should be:
pandoc +RTS -K64m -RTS file.html -f html -t mediawiki

**Comment by archonic** [comment]
I was wondering the same thing and went looking for the answer. It looks as if we can't set a flag with "+".

https://github.com/alphabetum/pandoc-ruby/blob/master/lib/pandoc-ruby.rb#L259

I would enjoy a way to set the command and its options in a less abstracted way. For now, it looks like we can get around the issue by setting options in the `pandoc_path`.

Before calling `convert`:
```
PandocRuby.pandoc_path = "pandoc +RTS -K64m -RTS"
```

**Comment by xwmx** [comment]
As of version 2.1.3, command line options specified as strings are passed to pandoc unaltered. So now the following should work:

```bash
PandocRuby.convert(@string, '+RTS', '-K64m', '-RTS', output: 'file.html', from: 'html', to: 'mediawiki')
```

Thanks!
