### ISSUE TITLE
Support for Pandoc "extensions"?

### ISSUE THREAD

**Issue by gwerbin** [xwmx/pandoc-ruby#25]
The Pandoc CLI has support for "extensions" to reader and writer formats that can be specified as a suffix to the "from" or "to" format name. For instance, in order to disable the "markdown_in_html_blocks" extension (doc: http://pandoc.org/MANUAL.html#raw-html), you would invoke Pandoc as:
```shell
pandoc -f markdown-markdown_in_html_blocks <etc.>
```

Is this possible currently? If not, how difficult would it be to support? There's a clear use case for it, at least downstream in the Jekyll plugin: https://github.com/mfenner/jekyll-pandoc/issues/10

In addition, Pandoc also has some pre-defined "styles" that gather up extensions into various Markdown flavors like GitHub and Multimarkdown: http://pandoc.org/MANUAL.html#markdown-variants. Could these also be added?

**Comment by jcn** [comment]
It appears that this can be done by passing the `from` and `to` params as strings instead of symbols and including all of the extension info in that string.

```ruby
PandocRuby.new(text, { from: "markdown-markdown_in_html_blocks", to: ... })
```

(commenting on this super old issue since I was looking for the same thing)

**Comment by xwmx** [comment]
Thanks! That's correct, @jcn. A new section with this information has been added to README.md:

https://github.com/xwmx/pandoc-ruby#extensions
