### ISSUE TITLE
How do you open a docx file?

### ISSUE THREAD

**Issue by burlesona** [xwmx/pandoc-ruby#27]
If you pass a docx file into PandocRuby, e.g.:

```ruby
PandocRuby.convert('./file.docx', :S, from: :docx, to: :html)
```
It errors with `RuntimeError: pandoc: Cannot read archive from stdin`

**Comment by abartov** [comment]
This is a problem in Pandoc itself:

https://github.com/jgm/pandoc/issues/3383

It is fixed in Pandoc 2.0.x.  Just upgrade your Pandoc binary and it'll work.

**Comment by agiratech-reddysai** [comment]
`gem 'pandoc-ruby', '2.0.2'`
same error raising `RuntimeError: pandoc: Cannot read archive from stdin`

**Comment by abartov** [comment]
@agiratech-reddysai - pandoc-ruby is just a wrapper gem around a system call, i.e. it runs the pandoc(1) binary on your system, so what matters is what version of pandoc is installed.  Try running `pandoc --version` from the command line, and upgrade **pandoc**, not **pandoc-ruby**, if necessary.

**Comment by archonic** [comment]
I'm running pandoc 2.2.1 and pandoc-ruby 2.0.2 and I'm having trouble getting a docx to convert to html as well (although obviously for a different reason).

The command line works. I'm using example_29.docx from the [pandoc demos](https://pandoc.org/demos.html). Running `docker-compose exec web pandoc -f docx -t html tmp/example29.docx` yields
```
<h1 id="synopsis">Synopsis</h1>
<p><code>pandoc</code> [<em>options</em>] [<em>input-file</em>]…</p>
<h1 id="description">Description</h1>
<p>Pandoc is a <a href="https://www.haskell.org">Haskell</a> library for converting from one markup format to another, and a command-line tool that uses this library.</p>
...
```

From the console however:
```
irb(main):001:0> PandocRuby
=> PandocRuby
irb(main):002:0> PandocRuby.convert("tmp/example29.docx", from: :docx, to: :html)
Traceback (most recent call last):
        1: from (irb):2
RuntimeError (couldn't parse docx file)
```

**Comment by xwmx** [comment]
Sorry for my absence, and I'm glad you were able to find a workaround. As of the latest version, [2.1.0](https://rubygems.org/gems/pandoc-ruby/versions/2.1.0), docx files can be converted by specifying the file path as an array:

```ruby
PandocRuby.new(['/path/to/example.docx'], from: 'docx', to: 'html').convert
```

Please let me know if you run into additional issues related to this!
