### ISSUE TITLE
DOCX to HTML

### ISSUE THREAD

**Issue by AaronDasani** [xwmx/pandoc-ruby#33]
Is there any way to convert a docx file to a html or textile format. I know PANDOC can do it because i done it in Javascript.

However it is being a pain in Ruby. I do have pandoc-ruby  in my gem file.
I saw in the pandoc-ruby documentation that you cannot convert docx  to anything.

If pandoc-ruby is a wrapper for PANDOC, isn't there a way to convert docx to html. Because, again PANDOC can do it, but the wrapper, pandoc-ruby can't.

Any help would be nice and appreciated.

**Comment by xwmx** [comment]
As of the latest version, [2.1.0](https://rubygems.org/gems/pandoc-ruby/versions/2.1.0), docx files can be converted using

```ruby
PandocRuby.new(['./test/files/reference.docx'], from: 'docx', to: 'html').convert
