### ISSUE TITLE
Improper handling of DOC file

### ISSUE THREAD

**Issue by archonic** [xwmx/pandoc-ruby#35]
Using pandoc directly I get this error when trying to convert a DOC file to HTML:
```
Pandoc can convert from DOCX, but not from DOC.
Try using Word to save your DOC file as DOCX, and convert that with pandoc.
```
Using pandoc-ruby I get this:
```
Errno::EPIPE: Broken pipe
from /usr/local/bundle/gems/pandoc-ruby-2.0.2/lib/pandoc-ruby.rb:209:in `write'
```
It would be handy to have a more detailed error to catch.

**Comment by xwmx** [comment]
Thanks for the heads up! There is slightly better error handling in the latest version, 2.1.0, that throws a RuntimeError and prints the error messages generated by pandoc. Please let me know if there is a better approach or if this doesn't work for you. Thanks!
