### ISSUE TITLE
Using Pathname objects for file arguments is broken in 2.1.2 and 2.1.3

### ISSUE THREAD

**Issue by mvz** [xwmx/pandoc-ruby#37]
Commit b2c0e4d2b932b5dcc29ed3e71985818f60d9f581 introduced a check if arguments contain whitespace. Before this change, any object supporting `#to_s` could be passed. Now, it has to support the `=~` operator. This means passing Pathname objects for path-like arguments is not broken.

Casting these arguments to strings (after then nil check, of course) would fix this.

**Comment by xwmx** [comment]
Thanks for the heads up! This should be fixed as of version 2.1.4. Let me know if you run into any more issues with this.

**Comment by mvz** [comment]
Thanks, @xwmx!

**Comment by archonic** [comment]
I'm using 2.16 and just hit this issue on the `V` argument.
This:
```
V: 'geometry:"top=1in, bottom=1.5in, left=1.5in, right=1.5in"'
```
Had to become this:
```
V: 'geometry:"top=1in,bottom=1.5in,left=1.5in,right=1.5in"'
```

**Comment by mvz** [comment]
@archonic I think that's an unrelated issue.
