### ISSUE TITLE
BUG: after last update get error.

### ISSUE THREAD

**Issue by ske42** [xwmx/pandoc-ruby#41]
Hello.
I've got a Redmine system which use this staff. 
After last update there is syntax error appeared. 
![image](https://user-images.githubusercontent.com/26792824/142872768-9569050c-56c7-4d6f-a09e-a1113686b933.png)

For while I've installed previous version, but there will be awesome if i'll can getting updates later. 

My system uses ruby 2.4.10p364 (2020-03-31 revision 67879) and

**Comment by xwmx** [comment]
@ske42 Thanks for the heads up! This should be resolved in version 2.1.6. Let me know if you continue to run into issues with this.

**Comment by ske42** [comment]
@xwmx, It seems to be working. Thank you.
