### ISSUE TITLE
Input file names with spaces are not quoted

### ISSUE THREAD

**Issue by offbyone** [xwmx/pandoc-ruby#45]
When running thusly:

```ruby
input_file = "input/roam/Electronics Tools.md"
PandocRuby.new([input_file], from: 'org', wrap: 'none').to_gfm
```

The underlying pandoc command will look like this:

```
pandoc input/roam/Electronics Tools.md --from "org" --wrap "none" --to "gfm"
```

This fails, obviously, because the filename isn't quoted.

**Comment by xwmx** [comment]
@offbyone Thanks! I updated the tests and this is now available in the latest release version, 2.1.9.
